project:
  name: smdinsole

spring:
  profiles:
    active: ${spring.profiles.active}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

sms:
  sendUrl: http://apis.aligo.in/send/
  key: 2ailet1dki7fa4pwkwu3em97krsdxn48
  userId: kokasinc
  sender: 07075252103
---
spring:
  config:
    activate:
      on-profile: local
logging:
  file:
    path: C:\home\smdinsole\logs\logback\
datasources:
  - name: kkokasin
    base-package: com.kokasin.insole.**.dao
    aop-execution: com.kokasin.insole..service.*.*(..)
    data-source:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:mysql://kkokasin-dev-db.cmcdolkwxf6m.ap-northeast-2.rds.amazonaws.com:3306/kkokasin?characterEncoding=UTF-8&serverTimezone=UTC&noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&autoReconnect=true
      username: kkokasin
      password: kkokasin21!
      maximumPoolSize: 5
server:
  url: api-dev.kokasin.com

---
spring:
  config:
    activate:
      on-profile: dev
logging:
  file:
    path: /home/ec2-user/logs/logback
datasources:
  - name: kkokasin
    base-package: com.kokasin.insole.**.dao
    aop-execution: com.kokasin.insole..service.*.*(..)
    data-source:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:mysql://kkokasin-dev-db.cmcdolkwxf6m.ap-northeast-2.rds.amazonaws.com:3306/kkokasin?characterEncoding=UTF-8&serverTimezone=UTC&noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&autoReconnect=true
      username: kkokasin
      password: kkokasin21!
      maximumPoolSize: 5
server:
  url: api-dev.kokasin.com
---
spring:
  config:
    activate:
      on-profile: prod
logging:
  file:
    path: /home/ec2-user/logs/logback
datasources:
  - name: kkokasin
    base-package: com.kokasin.insole.**.dao
    aop-execution: com.kokasin.insole..service.*.*(..)
    data-source:
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbcUrl: jdbc:log4jdbc:mysql://kkokasin-dev-db.cmcdolkwxf6m.ap-northeast-2.rds.amazonaws.com:3306/kkokasin?characterEncoding=UTF-8&serverTimezone=UTC&noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&autoReconnect=true
      username: kkokasin
      password: kkokasin21!
      maximumPoolSize: 5
server:
  url: api.kokasin.com